name: binder-env
dependencies:
  - cartopy
  - pandas
  - geopandas
  - pip
  - pip:
    - osmnx
    - folium
    - ipyleaflet
    - datasette
    - datasette-cluster-map
    - xlrd
    - geoplot
    - geovoronoi
    - geojson_rewind
    - csvs-to-sqlite
   - police-api-client
