name: binder-env
channels:
  - conda-forge
dependencies:
  - cartopy
  - pandas
  - geopandas
  - pip
  - pip:
    - git+https://github.com/gboeing/osmnx.git
    - folium
    - ipyleaflet
    - datasette
    - datasette-cluster-map
    - xlrd
    - geoplot
    - geovoronoi
    - geojson_rewind
    - csvs-to-sqlite
    - police-api-client
